### PR TITLE
Bunch of quality of life improvements.

### PR DESCRIPTION
**Pull request by YellowOnion**
Follow up to #1

### CODE REVIEW

**Comment by birkhofflee** [comment]
LGTM
Have you done the testings yet?

**Comment by birkhofflee** [comment]
Your version does not work for this image: https://i.imgur.com/QQGZpkj.png
Can you take a look of what's wrong?

**Comment by YellowOnion** [comment]
I converted about 8 different animations, I'm not sure why for this specific case it's not working hmm.

**Comment by YellowOnion** [comment]
Yesterday I wrote an app that uses fbchat to automate it even more, it does everything, just login with facebook details, send yourself a sticker, and it downloads, and animates it using imagemagick using the correct fps.

**Comment by YellowOnion** [comment]
I figured out the issues, and I fixed some readability issues.

**Pull request closed without merging**
